extends:
  - "react-app"
  - "airbnb"
  - "airbnb/hooks"
  - "prettier"
  - "prettier/react"

plugins:
  - "@typescript-eslint"
  - "cypress"
  - "prettier"

parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 8

env:
  browser: true
  cypress/globals: true
  es6: true

settings:
  import/resolver:
    node:
      paths: [src]
      extensions: [.js, .jsx, .ts, .tsx]

rules:
  class-methods-use-this: 0
  consistent-return: 0
  import/no-extraneous-dependencies: [error, {devDependencies: ["**/*.e2e.ts", "cypress/**/*.js"]}]
  import/prefer-default-export: 0
  jsx-a11y/label-has-associated-control: 0
  jsx-a11y/no-autofocus: 0
  max-classes-per-file: 0
  no-console: 0
  no-empty-function: 0
  no-shadow: 0
  no-underscore-dangle: 0
  no-use-before-define: 0
  no-useless-constructor: 0
  prefer-template: 0
  prettier/prettier: error
  react-hooks/exhaustive-deps: warn
  react-hooks/rules-of-hooks: error
  react/destructuring-assignment: 0
  react/jsx-filename-extension: [1, {extensions: [.tsx]}]
  react/jsx-one-expression-per-line: 0
  react/jsx-props-no-spreading: 0
  react/no-danger: 0
  react/prop-types: 0
  space-in-brackets: 0
