name: tests

on:
  pull_request:
  push:
    branches:
    - master

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install lib dependencies
      working-directory: lib
      run: yarn
    - name: Build lib
      working-directory: lib
      run: yarn build
    - name: Install demo dependencies
      working-directory: demo
      run: yarn
    - name: Run demo
      working-directory: demo
      run: yarn start &
    - name: Run tests
      working-directory: lib
      run: yarn test
    - uses: codecov/codecov-action@v2
